//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Table
    {
        public string Name { get; set; }
        public string Last_Name { get; set; }
        public string National_Code { get; set; }
        public string ID { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Gender { get; set; }
        public string Phone_Num { get; set; }
        public string Address { get; set; }
        public string Vaccine_Name { get; set; }
        public int Doses_Num { get; set; }
        public System.DateTime Dose1_Date { get; set; }
        public System.DateTime Dose2_Date { get; set; }
    }
}
