//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccine_Table
    {
        public string Vaccine_Name { get; set; }
        public int Doses_Num { get; set; }
        public string Country_Of_Export { get; set; }
    }
}
